name: Docker Project Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            build-args: |
              VUE_APP_API_URL=${{ vars.API_PREFIX_PROD }}
            push: true
            tags: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest

  run-trivy-scan-backend:
    name: Run Trivy scan for Backend
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Pull Backend image
        run: docker pull ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
      - name: Run Trivy scan backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-backend:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true


  run-trivy-scan-frontend:
    name: Run Trivy scan for Frontend
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Pull Frontend image
        run: docker pull ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
      - name: Run Trivy scan frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USER }}/docker-project-frontend:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: true

  run-with-docker-compose:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build via Docker Compose
        uses: hoverkraft-tech/compose-action@v2.2.0